name: UltimatePvP
main: MCPH\UltimatePvP\Main
version: 1.0
api: 1.13.0
author: MinecrafterPH
description: PvP just got better!
website: www.minecrafterph.tk

commands:
  kills:
    description: "Shows your number of kills."
    
permissions:
  stats.kills:
    description: Allows to show your number of kills.
    default: true
